### PR TITLE
Bump clevertap-android-sdk from 3.9.1 to 4.0.0

### PR DESCRIPTION
**Pull request by darshanclevertap**
Bumped up the CT Android SDK version to v4.0.0 and fixed one breaking change as a part of major release.
Please merge this and close the dependabot PR

### CODE REVIEW

**Comment by darshanclevertap** [comment]
@samdozor Can we get this PR merged?

**Comment by darshanclevertap** [comment]
@willpassidomo Can we get this PR merged?

**Review by willpassidomo — APPROVED** [review]
Looks good to me. Sorry for the wait for the review, this didn't pop up on our channel :/

**Comment by darshanclevertap** [comment]
@willpassidomo Thanks for getting this close and not a problem, going forward I'll change the dependency to `4.+` so that the `dependabot` flow can do its thing.

**Pull request merged**
